import tomllib
from pathlib import Path
from typing import Any, Mapping

import yaml

ADDITIONS = "additions"
DELETIONS = "deletions"
CONVERSIONS = "conversions"
PIP_REQUIREMENTS = "pip-requirements"

PROJECT_NAME = "pyproject-to-conda-env"


def read_pyproject(path: str | Path = "pyproject.toml") -> dict[str, Any]:
    """Read the pyproject file as dict"""
    with open(path, "rb") as file:
        return tomllib.load(file)


def read_transform(path: str | Path) -> dict[str, Any]:
    """Read the transformation YAML file"""
    with open(path, "r") as file:
        return yaml.safe_load(file) or {}


def assert_transform(transform: dict[str, Any]):
    """Assert transformation structure"""
    assert "name" in transform
    assert isinstance(transform["name"], str)
    assert "channels" in transform
    assert isinstance(transform["channels"], list)
    assert ADDITIONS in transform
    assert DELETIONS in transform
    assert CONVERSIONS in transform
    assert PIP_REQUIREMENTS in transform


def read_dependencies(
    pyproj_data: dict[str, Any], optional_dependencies: bool | list[str]
) -> list[str]:
    """Read all dependencies (also optional) and merge them"""
    dependencies: list[str] = pyproj_data["project"]["dependencies"].copy()
    if not optional_dependencies:
        return dependencies

    opt_deps = pyproj_data["project"].get("optional-dependencies", {})
    dep_groups = list(opt_deps.keys())
    if isinstance(optional_dependencies, list):
        if not opt_deps:
            raise RuntimeError("No optional dependencies found in pyproject data")
        dep_groups = optional_dependencies
    elif not opt_deps:
        return dependencies

    # optional_dependencies is True: Take all that are listed
    for group in dep_groups:
        dependencies.extend(opt_deps[group])

    return dependencies


def remove_dependencies(dep_list: list[str], deletions: list[str] | None) -> list[str]:
    """Remove dependencies"""
    if deletions is None:
        return dep_list.copy()

    def delete(dependency: str) -> bool:
        for dep in deletions:
            if dep in dependency:
                return True
        return False

    return [dep for dep in dep_list if not delete(dep)]


def convert_dependencies(
    dep_list: list[str], conversion_table: Mapping[str, str] | None
) -> list[str]:
    """Convert dependency names"""
    if conversion_table is None:
        return dep_list.copy()

    def convert(dependency: str) -> str:
        for dep_from, dep_to in conversion_table.items():
            if dep_from in dependency:
                return dependency.replace(dep_from, dep_to)
        return dependency

    return [convert(dep) for dep in dep_list]


def add_dependencies(
    dep_list: list[str], additions: list[str] | None, pip_requirements: list[str] | None
) -> list[str]:
    """Add dependencies"""
    dep_list = dep_list.copy()
    if additions:
        dep_list.extend(additions)
    if pip_requirements:
        # NOTE: Need to keep the deleted entries to preserve version specs
        dep_list_no_pip = remove_dependencies(dep_list, pip_requirements)
        pip_reqs_with_versions = list(set(dep_list) - set(dep_list_no_pip))

        def version_given(dependency: str) -> bool:
            for dep_ver in pip_reqs_with_versions:
                if dependency in dep_ver:
                    return True
            return False

        pip_reqs_without_versions = [
            dep for dep in pip_requirements if not version_given(dep)
        ]
        pip_reqs = pip_reqs_with_versions + pip_reqs_without_versions
        if not pip_reqs:
            pass

        if "pip" not in dep_list:
            dep_list_no_pip.append("pip")
        dep_list_no_pip.append({"pip": sorted(pip_reqs)})
        dep_list = dep_list_no_pip
    return dep_list


def write_environment_file(
    dependencies: list[str | dict[str, list[str]]],
    output_path: str | Path,
    name: str,
    channels: list[str],
):
    """Write the conda environment file"""
    # Merge content
    data = {
        "name": name,
        "channels": channels,
        "dependencies": dependencies,
    }
    content = yaml.dump(data)
    content = (
        "# DO NOT MODIFY!\n"
        f"# This file was automatically generated by '{PROJECT_NAME}'\n"
    ) + content

    # Write file
    with open(output_path, "w") as file:
        file.writelines(content)
